version: "3.2"
services:
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./src/nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #TODO: agregar servicios de los que depende

  backend:
    image: python:3.10
    volumes:
       - ./src/backend:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    # depends_on:
    #   - database
  # broker:
  #TODO: agregar servicio de broker
  # database:
  #TODO: agregar servicio de base de datos
  # worker:
  #TODO: agregar servicio de worker