version: "3.2"
services:
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    #TODO: agregar servicios de los que depende

  backend:
  #TODO: agregar servicio de backend
  broker:
  #TODO: agregar servicio de broker
  database:
  #TODO: agregar servicio de base de datos
  worker:
  #TODO: agregar servicio de worker